---
permalink: rhel-install/task-reset-the-admin-password-created-during-installation-linux.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Se si dimentica la password dell"utente amministratore creata durante l"installazione del server OnCommand Workflow Automation (WFA), è possibile reimpostarla.' 
---
= Reimpostare la password admin creata durante l'installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dimentica la password dell'utente amministratore creata durante l'installazione del server OnCommand Workflow Automation (WFA), è possibile reimpostarla.

* È necessario disporre dei privilegi di root per il sistema Linux su cui è stato installato WFA.
* I servizi WFA devono essere in esecuzione.
* Questa procedura ripristina solo la password dell'utente amministratore creata durante l'installazione WFA.
+
Non è possibile reimpostare la password di altri utenti amministratori WFA creati dopo l'installazione di WFA.

* Questa procedura non applica il criterio password configurato.
+
Pertanto, è necessario immettere una password conforme alla policy sulla password o modificarla dall'interfaccia utente WFA dopo aver reimpostato la password.



.Fasi
. Come utente root, accedere al sistema Linux su cui è installato WFA.
. Al prompt della shell, accedere alla seguente directory sul server WFA: WFA_install_location/wfa/bin/
. Immettere il seguente comando:
+
`./wfa --admin-password [--password=PASS]`

+
Se non è stata fornita una password, è necessario immetterla quando richiesto.

. Al prompt della shell, seguire le istruzioni a schermo.

