---
permalink: rhel-install/task-replace-the-default-workflow-automation-ssl-certificate-linux.html 
sidebar: sidebar 
keywords: replace, default, workflow, automation, ssl, certificate 
summary: 'È possibile sostituire il certificato SSL predefinito di Workflow Automation (WFA) se il certificato è scaduto o se si desidera aumentare il periodo di validità del certificato.' 
---
= Sostituire il certificato SSL predefinito di Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire il certificato SSL predefinito di Workflow Automation (WFA) se il certificato è scaduto o se si desidera aumentare il periodo di validità del certificato.

È necessario disporre dei privilegi di root per il sistema Linux su cui è stato installato WFA.

In questa procedura viene utilizzato il percorso di installazione predefinito di WFA. Se è stata modificata la posizione predefinita durante l'installazione, è necessario utilizzare il percorso di installazione WFA personalizzato.

.Fasi
. Accedere come utente root sul computer host WFA.
. Al prompt della shell, accedere alla seguente directory sul server WFA: WFA_install_location/wfa/bin
. Arrestare i servizi del server e del database WFA:
+
`./wfa --stop=WFA`

+
`./wfa --stop=DB`

. Eliminare il file wfa.keystore dalla seguente posizione: WFA_install_location/wfa/jboss/standalone/Configuration/keystore.
. Aprire un prompt della shell sul server WFA e modificare le directory nel percorso seguente: <OpenJDK_install_location>/bin
. Ottenere la chiave del database:
+
`keytool -keysize 2048 -genkey -alias "ssl keystore" -keyalg RSA -keystore "WFA_install_location/wfa/jboss/standalone/configuration/keystore/wfa.keystore" -validity xxxx`

+
xxxx indica il numero di giorni di validità del nuovo certificato.

. Quando richiesto, inserire la password (predefinita o nuova).
+
La password predefinita è una password crittografata generata in modo casuale.

+
Per ottenere e decrittare la password predefinita, seguire la procedura descritta nell'articolo della Knowledge base link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["Come rinnovare il certificato autofirmato su WFA 5.1.1.0.4"^]

+
Per utilizzare una nuova password, seguire la procedura descritta nell'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_update_a_new_password_for_the_keystore_in_WFA["Come aggiornare una nuova password per il keystore in WFA."^]

. Inserire i dettagli richiesti per il certificato.
. Esaminare le informazioni visualizzate, quindi immettere `Yes`.
. Premere *Invio* quando richiesto dal seguente messaggio: Inserire la password della chiave per <SSL keystore> <RETURN if same as keystore password>.
. Riavviare i servizi WFA:
+
`./wfa --start=DB`

+
`./wfa --start=WFA`


