---
permalink: rhel-install/task-back-up-the-wfa-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: back up, restore, oncommand, workflow, automation, database, configurations, linux 
summary: 'È possibile eseguire il backup e il ripristino del database OnCommand Workflow Automation (Wfa) e delle configurazioni supportate in modo da poter ripristinare i dati in caso di disastro. Le configurazioni supportate includono accesso ai dati, timeout HTTP e certificati SSL.' 
---
= Eseguire il backup e il ripristino del database e delle configurazioni OnCommand Workflow Automation su Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il backup e il ripristino del database OnCommand Workflow Automation (Wfa) e delle configurazioni supportate in modo da poter ripristinare i dati in caso di disastro. Le configurazioni supportate includono accesso ai dati, timeout HTTP e certificati SSL.

È necessario disporre dei privilegi di amministratore o delle credenziali Architect.

È necessario creare il backup in una posizione sicura, in quanto il ripristino del backup consente di accedere a tutti i sistemi di storage a cui si accede da WFA.

[NOTE]
====
* Durante il disaster recovery è necessario eseguire un backup completo dei database e delle configurazioni WFA, che può essere utilizzato sia in ambienti standalone che ad alta disponibilità.
* È possibile utilizzare solo i comandi CLI o le API REST per operazioni complete di backup e ripristino durante il disaster recovery.
+
Non è possibile utilizzare l'interfaccia utente Web per eseguire il backup o il ripristino del database WFA durante il disaster recovery.



====
.Fasi
. Eseguire il backup del database OnCommand Workflow Automation.
+
link:reference-backing-up-of-the-oncommand-workflow-automation-database.html["Backup del database OnCommand Workflow Automation"]

. Ripristinare un backup precedente del database OnCommand Workflow Automation.
+
link:concept-restoring-the-wfa-database.html["Ripristino del database OnCommand Workflow Automation"]


