---
permalink: rhel-install/task-restore-full-the-oncommand-workflow-automation-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, restore, wfa, database, cli 
summary: 'È possibile eseguire un ripristino completo del database OnCommand Workflow Automation (Wfa) e delle configurazioni supportate di cui è stato eseguito il backup in precedenza utilizzando l"interfaccia a riga di comando (CLI). In un ripristino completo, è possibile ripristinare il database WFA, la configurazione WFA e la chiave.' 
---
= Ripristinare (pieno) il database WFA utilizzando la CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire un ripristino completo del database OnCommand Workflow Automation (Wfa) e delle configurazioni supportate di cui è stato eseguito il backup in precedenza utilizzando l'interfaccia a riga di comando (CLI). In un ripristino completo, è possibile ripristinare il database WFA, la configurazione WFA e la chiave.

* È necessario aver creato un backup del database WFA.
* È necessario disporre delle credenziali di amministratore o architetto.


.Fasi
. Al prompt della shell, accedere alla seguente directory sul server WFA: WFA_install_location/wfa/bin
+
wfa_install_location è la directory di installazione di WFA.

. Ripristinare il database WFA:
+
`wfa --restore --full --user=user_name [--password=password] [--location=path] --restart`

+
** user_name è il nome utente dell'utente admin o architect.
** password è la password dell'utente.
+
Se la password non è stata fornita, è necessario immetterla quando richiesto.

** percorso è il percorso completo della directory per il file di ripristino.


. Verificare che l'operazione di ripristino sia riuscita e che WFA sia accessibile.

