---
permalink: rhel-install/task-modify-the-default-password-policy-linux.html 
sidebar: sidebar 
keywords: modify, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) è configurato per applicare una policy sulle password per gli utenti locali. È possibile modificare il criterio password predefinito.' 
---
= Modificare il criterio password predefinito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) è configurato per applicare una policy sulle password per gli utenti locali. È possibile modificare il criterio password predefinito.

È necessario aver effettuato l'accesso al sistema host WFA come utente root.

* In questa procedura viene utilizzato il percorso di installazione predefinito di WFA.
+
Se è stata modificata la posizione predefinita durante l'installazione, è necessario utilizzare il percorso di installazione WFA modificato.

* Il comando per il criterio password predefinito è ./wfa --password-policy=default.
+
L'impostazione predefinita è "`minLength=true,8;specialeChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whitespaceChar=false`" . Questo indica che la policy predefinita per la password deve avere una lunghezza minima di otto caratteri, deve contenere almeno 1 carattere speciale, 1 cifra, 1 carattere minuscolo, 1 carattere maiuscolo e nessun spazio.



.Fasi
. Al prompt della shell, accedere alla seguente directory sul server WFA: WFA_install_location/wfa/bin/
. Modificare il criterio password predefinito immettendo il seguente comando:
+
`./wfa --password-policy=PasswordPolicyString --restart=WFA`


