---
permalink: rhel-install/task-create-a-certificate-signing-request-for-workflow-automation-linux.html 
sidebar: sidebar 
keywords: workflow, automation, wfa, linux, create, certificate, sign, request 
summary: 'È possibile creare una richiesta di firma del certificato (CSR) in Linux in modo da poter utilizzare il certificato SSL firmato da un"autorità di certificazione (CA) invece del certificato SSL predefinito per Workflow Automation (Wfa).' 
---
= Creare una richiesta di firma del certificato per Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una richiesta di firma del certificato (CSR) in Linux in modo da poter utilizzare il certificato SSL firmato da un'autorità di certificazione (CA) invece del certificato SSL predefinito per Workflow Automation (Wfa).

* È necessario disporre dei privilegi di root per il sistema Linux su cui è stato installato WFA.
* È necessario sostituire il certificato SSL predefinito fornito da WFA.


In questa procedura viene utilizzato il percorso di installazione predefinito di WFA. Se il percorso predefinito è stato modificato durante l'installazione, è necessario utilizzare il percorso di installazione WFA personalizzato.

.Fasi
. Accedere come utente root sul computer host WFA.
. Aprire un prompt della shell sul server WFA e modificare le directory nel percorso seguente: <OpenJDK_install_location>/bin
. Creare un file CSR:
+
`keytool -certreq -keystore WFA_install_location/wfa/jboss/standalone/configuration/keystore/wfa.keystore -alias "ssl keystore" -file /root/file_name.csr`

+
File_name è il nome del file CSR.

. Quando richiesto, inserire la password (predefinita o nuova).
+
La password predefinita è una password crittografata generata in modo casuale.

+
Per ottenere e decrittare la password predefinita, seguire la procedura descritta nell'articolo della Knowledge base link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["Come rinnovare il certificato autofirmato su WFA 5.1.1.0.4"^]

+
Per utilizzare una nuova password, seguire la procedura descritta nell'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_update_a_new_password_for_the_keystore_in_WFA["Come aggiornare una nuova password per il keystore in WFA."^]

. Inviare il file nome_file.csr alla CA per ottenere un certificato firmato.
+
Per ulteriori informazioni, visitare il sito Web della CA.

. Scarica un certificato di catena dalla CA, quindi importa il certificato di catena nel keystore:
+
`keytool -import -alias "ssl keystore CA certificate" -keystore WFA_install_location/wfa/jboss/standalone/configuration/keystore/wfa.keystore" -trustcacerts -file chain_cert.cer`

+
`chain_cert.cer` È il file di certificato di catena ricevuto dalla CA. Il file deve essere in formato X.509.

. Importare il certificato firmato ricevuto dalla CA:
+
`keytool -import -alias "ssl keystore" -keystore WFA_install_location/wfa/jboss/standalone/configuration/keystore/wfa.keystore" -trustcacerts -file certificate.cer`

+
`certificate.cer` È il file di certificato di catena ricevuto dalla CA.

. Avviare i servizi WFA:
+
`./wfa --start=DB`

+
`./wfa --start=WFA`


