---
permalink: rhel-install/task-configure-a-database-user-by-running-ocsetup-on-windows.html 
sidebar: sidebar 
keywords: configure, database, user, run, ocsetup, windows 
summary: 'È possibile eseguire il file ocsetup sul server DataFabric Manager 5.x per configurare l"accesso in sola lettura del database DataFabric Manager 5.x su OnCommand Workflow Automation.' 
---
= Configurare un utente di database eseguendo ocsetup su Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il file ocsetup sul server DataFabric Manager 5.x per configurare l'accesso in sola lettura del database DataFabric Manager 5.x su OnCommand Workflow Automation.

.Fasi
. Scaricare il file wfa_ocsetup.exe in una directory del server DataFabric Manager 5.x dal seguente percorso:
+
+https://WFA_Server_IP/download/wfa_ocsetup.exe.+

+
_WFA_Server_IP_ è l'indirizzo IP (indirizzo IPv4 o IPv6) del server WFA.

+
Se è stata specificata una porta non predefinita per WFA, è necessario includere il numero della porta come segue:

+
+https://wfa_server_ip:port/download/wfa_ocsetup.exe.+

+
_Port_ è il numero di porta TCP utilizzato per il server WFA durante l'installazione.

+
Se si specifica un indirizzo IPv6, è necessario racchiuderlo tra parentesi quadre.

. Fare doppio clic sul file wfa_ocsetup.exe.
. Leggere le informazioni nella procedura di installazione guidata e fare clic su *Avanti*.
. Cercare o digitare la posizione di OpenJDK e fare clic su *Avanti*.
. Immettere un nome utente e una password per ignorare le credenziali predefinite.
+
Viene creato un nuovo account utente del database con accesso al database DataFabric Manager 5.x.

+

NOTE: Se non si crea un account utente, vengono utilizzate le credenziali predefinite. Per motivi di sicurezza, è necessario creare un account utente.

. Fare clic su *Avanti* e rivedere i risultati.
. Fare clic su *Avanti*, quindi su *fine* per completare la procedura guidata.

