---
permalink: windows-install/task-configure-autosupport.html 
sidebar: sidebar 
keywords: configure, autosupport 
summary: 'È possibile configurare diverse impostazioni AutoSupport, ad esempio la pianificazione, il contenuto dei messaggi AutoSupport e il server proxy. AutoSupport invia registri settimanali dei contenuti selezionati al supporto tecnico per l"archiviazione e l"analisi dei problemi.' 
---
= Configurare AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare diverse impostazioni AutoSupport, ad esempio la pianificazione, il contenuto dei messaggi AutoSupport e il server proxy. AutoSupport invia registri settimanali dei contenuti selezionati al supporto tecnico per l'archiviazione e l'analisi dei problemi.

.Fasi
. Accedere a WFA tramite un browser Web come amministratore.
. Fare clic su *Impostazioni* e sotto *Configurazione* fare clic su *AutoSupport*.
. Assicurarsi che la casella *Enable AutoSupport* (attiva protocollo) sia selezionata.
. Inserire le informazioni richieste.
. Selezionare una delle seguenti opzioni dall'elenco *contenuto*:
+
[cols="2*"]
|===
| Se si desidera includere... | Quindi scegliere questa opzione... 


 a| 
Solo i dettagli di configurazione, ad esempio utenti, flussi di lavoro e comandi dell'installazione WFA
 a| 
`send only configuration data`



 a| 
Dettagli di configurazione WFA e dati nelle tabelle della cache WFA, come lo schema
 a| 
`send configuration and cache data` (impostazione predefinita)



 a| 
Dettagli sulla configurazione DI WFA, dati nelle tabelle della cache WFA e dati nella directory di installazione
 a| 
`send configuration and cache extended data`

|===
+

NOTE: La password di qualsiasi utente WFA è _non_ inclusa nei dati AutoSupport.

. Verificare che sia possibile scaricare un messaggio AutoSupport:
+
.. Fare clic su *Download*.
.. Nella finestra di dialogo visualizzata, selezionare la posizione in cui salvare il file .7z.


. Verificare l'invio di un messaggio AutoSupport alla destinazione specificata facendo clic su *Invia ora*.
. Fare clic su *Save* (Salva).

