---
permalink: windows-install/task-create-a-certificate-signing-request-for-workflow-automation-windows.html 
sidebar: sidebar 
keywords: workflow, automation, wfa, windows, create, certificate, sign, request 
summary: 'È possibile creare una richiesta di firma del certificato (CSR) in Windows in modo da poter utilizzare il certificato SSL firmato da un"autorità di certificazione (CA) invece del certificato SSL predefinito per Workflow Automation (Wfa).' 
---
= Creare una richiesta di firma del certificato per Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una richiesta di firma del certificato (CSR) in Windows in modo da poter utilizzare il certificato SSL firmato da un'autorità di certificazione (CA) invece del certificato SSL predefinito per Workflow Automation (Wfa).

* È necessario disporre dei privilegi di amministratore di Windows sul server WFA.
* È necessario sostituire il certificato SSL predefinito fornito da WFA.


In questa procedura viene utilizzato il percorso di installazione predefinito di WFA. Se il percorso predefinito è stato modificato durante l'installazione, è necessario utilizzare il percorso di installazione WFA personalizzato.

.Fasi
. Accedere come utente amministratore sul computer host WFA.
. Aprire un prompt dei comandi sul server WFA, quindi modificare le directory nella posizione seguente: + <OpenJDK_install_location>
. Creare una CSR:
+
`keytool -certreq -keystore WFA_install_location\WFA\jboss\standalone\configuration\keystore\wfa.keystore -alias "ssl keystore" -file C:\file_name.csr`

+
File_name è il nome del file CSR.

. Quando richiesto, inserire la password (predefinita o nuova).
+
La password predefinita è una password crittografata generata in modo casuale.

+
Per ottenere e decrittare la password predefinita, seguire la procedura descritta nell'articolo della Knowledge base link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["Come rinnovare il certificato autofirmato su WFA 5.1.1.0.4"^]

+
Per utilizzare una nuova password, seguire la procedura descritta nell'articolo della Knowledge base link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_update_a_new_password_for_the_keystore_in_WFA["Come aggiornare una nuova password per il keystore in WFA."^]

. Inviare il file nome_file.csr alla CA per ottenere un certificato firmato.
+
Per ulteriori informazioni, visitare il sito Web della CA.

. Scarica un certificato di catena dalla CA, quindi importa il certificato di catena nel keystore: `keytool -import -alias "ssl keystore CA certificate" -keystore "WFA_install_location\WFA\jboss\standalone\configuration\keystore\wfa.keystore" -trustcacerts -file C:\chain_cert.cer`
+
C: Il file del certificato di catena ricevuto dalla CA. Il file deve essere in formato X.509.

. Importare il certificato firmato ricevuto dalla CA:
+
`keytool -import -alias "ssl keystore" -keystore "WFA_install_location\WFA\jboss\standalone\configuration\keystore\wfa.keystore" -file C:\certificate.cer`

+
C: Il file del certificato di catena ricevuto dalla CA.

. Avviare i seguenti servizi WFA:
+
** Database NetApp WFA
** Server NetApp WFA



