---
permalink: windows-install/task-restrict-access-rights-of-oncommand-workflow-automation-on-the-host.html 
sidebar: sidebar 
keywords: restrict, access rights, oncommand, workflow, automation, host 
summary: 'Per impostazione predefinita, OnCommand Workflow Automation (Wfa) esegue i flussi di lavoro come amministratore del sistema host. È possibile limitare i diritti WFA sul sistema host modificando le impostazioni predefinite.' 
---
= Limitare i diritti di accesso di OnCommand Workflow Automation sull'host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, OnCommand Workflow Automation (Wfa) esegue i flussi di lavoro come amministratore del sistema host. È possibile limitare i diritti WFA sul sistema host modificando le impostazioni predefinite.

È necessario aver effettuato l'accesso al sistema host WFA come amministratore.

.Fasi
. Creare un nuovo account utente Windows con autorizzazioni per aprire socket e scrivere nella home directory Wfa.
. Aprire la console dei servizi Windows utilizzando Services.msc e fare doppio clic su *NetApp WFA Database*.
. Fare clic sulla scheda *Log on* (accesso).
. Selezionare *questo account* e immettere le credenziali del nuovo utente creato, quindi fare clic su *OK*.
. Fare doppio clic su *NetApp WFA Server*.
. Fare clic sulla scheda *Log on* (accesso).
. Selezionare *questo account* e immettere le credenziali del nuovo utente creato, quindi fare clic su *OK*.
. Riavviare i servizi * NetApp WFA Database* e * NetApp WFA Server*.

