---
permalink: windows-install/task-reset-the-admin-password-created-during-installation.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Se si dimentica la password dell"utente amministratore creata durante l"installazione del server OnCommand Workflow Automation (Wfa), è possibile reimpostarla.' 
---
= Reimpostare la password admin creata durante l'installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dimentica la password dell'utente amministratore creata durante l'installazione del server OnCommand Workflow Automation (Wfa), è possibile reimpostarla.

* È necessario disporre dei privilegi di amministratore per il sistema Windows su cui è stato installato WFA.
* I servizi WFA devono essere in esecuzione.
* Questa procedura ripristina solo la password dell'utente amministratore creata durante l'installazione di WFA.
+
Non è possibile reimpostare la password di altri utenti amministratori WFA creati dopo l'installazione di WFA.

* Questa procedura non applica il criterio password configurato.
+
Dopo aver reimpostato la password, è necessario immettere una password conforme alla policy sulla password o modificarla dall'interfaccia utente WFA.



.Fasi
. Aprire un prompt dei comandi e accedere alla seguente directory: `WFA_install_location\WFA\bin\`
. Immettere il seguente comando:
+
`wfa --admin-password [--password=PASS]`

+
Se non si immette una password nel comando, è necessario immetterla quando richiesto.

. Al prompt dei comandi, seguire le istruzioni visualizzate sullo schermo per reimpostare la password admin.

