---
permalink: windows-install/task-modify-the-default-password-policy-windows.html 
sidebar: sidebar 
keywords: modify, default, password policy, windows 
summary: 'OnCommand Workflow Automation (Wfa) applica una policy sulle password per gli utenti locali. È possibile modificare il criterio password predefinito per impostare una password in base alle proprie esigenze.' 
---
= Modificare il criterio password predefinito per Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (Wfa) applica una policy sulle password per gli utenti locali. È possibile modificare il criterio password predefinito per impostare una password in base alle proprie esigenze.

È necessario accedere al sistema host WFA come utente root.

* In questa procedura viene utilizzato il percorso di installazione predefinito di WFA.
+
Se è stata modificata la posizione predefinita durante l'installazione, è necessario utilizzare il percorso di installazione WFA personalizzato.

* Il comando per modificare il criterio password predefinito è ..wfa --password-policy=default.
+
L'impostazione predefinita è "`minLength=true,8;specialeChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whitespaceChar=false`". In base a questa impostazione per il criterio password predefinito, la password deve avere una lunghezza minima di otto caratteri, deve contenere almeno un carattere speciale, una cifra, un carattere minuscolo e un carattere maiuscolo e non deve contenere spazi.



.Fasi
. Al prompt dei comandi, accedere alla seguente directory sul server WFA:
+
`WFA_install_location/wfa/bin/`

. Modificare il criterio password predefinito:
+
`.\wfa --password-policy=PasswordPolicyString --restart=WFA`


