---
permalink: windows-install/task-disable-the-default-password-policy.html 
sidebar: sidebar 
keywords: disable, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) è configurato per applicare una policy sulle password per gli utenti locali. Se non si desidera utilizzare il criterio password, è possibile disattivarlo.' 
---
= Disattiva il criterio password predefinito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) è configurato per applicare una policy sulle password per gli utenti locali. Se non si desidera utilizzare il criterio password, è possibile disattivarlo.

È necessario aver effettuato l'accesso al sistema host WFA come amministratore.

In questa procedura viene utilizzato il percorso di installazione predefinito di WFA. Se è stata modificata la posizione predefinita durante l'installazione, è necessario utilizzare il percorso di installazione WFA modificato.

.Fasi
. Aprire Esplora risorse e accedere alla seguente directory: `WFA_install_location\WFA\bin\.`
. Fare doppio clic sul file ps.cmd.
+
Viene visualizzato un prompt dell'interfaccia a riga di comando (CLI) PowerShell con i moduli ONTAP e WFA caricati.

. Quando richiesto, immettere quanto segue:
+
`Set-WfaConfig -Name PasswordPolicy -Enable $false`

. Quando richiesto, riavviare i servizi WFA.

