---
permalink: help/reference-edit-credentials-dialog-box.html 
sidebar: sidebar 
keywords: edit, credential, dialog box, enable, modify, exist 
summary: La finestra di dialogo Modifica credenziali consente di modificare una credenziale esistente. 
---
= Finestra di dialogo Edit Credentials (Modifica credenziali)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Modifica credenziali consente di modificare una credenziale esistente.



== Parametri delle credenziali

* *Corrispondenza*
+
Consente di selezionare il tipo di corrispondenza della credenziale, che definisce la credenziale per un indirizzo IP o un nome host specifico o per un'intera subnet o intervallo IP. Le opzioni disponibili includono:

+
** Esatto: Definisce un indirizzo IP o un nome host specifico
** Modello: Definisce un'intera subnet o un intervallo IP


* *Tipo*
+
Consente di selezionare il tipo di credenziale dall'elenco a discesa.

+
VMware vCenter non è supportato per Linux.

* *Nome/IP*
+
Consente di specificare il nome host o l'indirizzo IP per la credenziale.

* *Nome utente*
+
Consente di specificare il nome utente per la credenziale.

* *Password*
+
Consente di specificare la password per il nome utente.

* *Sovrascrivi valori predefiniti*
+
Consente di sovrascrivere i valori predefiniti del protocollo, della porta e del timeout associati al tipo di sistema remoto selezionato per la credenziale.

+
Per impostazione predefinita, questa casella di controllo non è selezionata. Selezionare la casella di controllo se si desidera sovrascrivere i valori predefiniti.





== Tabella dei protocolli

La tabella dei protocolli visualizza i numeri di porta e i limiti di timeout (in secondi) per i protocolli associati al sistema remoto selezionato per la credenziale.



== Pulsanti di comando

* *Test*
+
Consente di verificare la connessione al nome host o all'indirizzo IP effettuando l'accesso utilizzando le credenziali richieste.

* *Salva*
+
Salva le impostazioni di configurazione e chiude la finestra di dialogo.

* *Annulla*
+
Annulla le modifiche, se presenti, e chiude la finestra di dialogo.


