---
permalink: help/reference-clone-category-dialog-box.html 
sidebar: sidebar 
keywords: clone, category, dialog box, enable, copy, workflow 
summary: 'La finestra di dialogo Clone Category (Copia categoria) consente di copiare una categoria del flusso di lavoro e di modificarla.' 
---
= Finestra di dialogo Clona categoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Clone Category (Copia categoria) consente di copiare una categoria del flusso di lavoro e di modificarla.

* *Nome*
+
Consente di modificare il nome della categoria. Il nome della categoria selezionata per la clonazione viene utilizzato come nome per il clone e aggiunto con - copy per impostazione predefinita.

* *Descrizione*
+
Consente di immettere una descrizione per la categoria.

* *Flussi di lavoro disponibili*
+
Visualizza tutti i flussi di lavoro disponibili che non vengono spostati nella casella flussi di lavoro selezionati.

* *Flussi di lavoro selezionati*
+
Visualizza tutti i flussi di lavoro selezionati per la categoria.

* *Categoria utilizzata per l'autorizzazione del flusso di lavoro*
+
Consente di selezionare gli utenti con ruolo di operatore che possono eseguire la categoria. Per impostazione predefinita, la casella di controllo non è selezionata e la categoria è disponibile per tutti gli utenti.

* *Operatori disponibili*
+
Visualizza tutti gli utenti con ruolo operatore.

* *Operatori selezionati*
+
Visualizza gli utenti autorizzati a eseguire la categoria.





== Pulsanti di comando

* *Pulsanti di selezione*
+
Consente di spostare la voce selezionata da una casella all'altra.

* *Salva*
+
Salva la categoria e chiude la finestra di dialogo.

* *Annulla*
+
Non salva la categoria e chiude la finestra di dialogo.


