---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: La finestra di dialogo nuove credenziali consente di creare una nuova credenziale. 
---
= Finestra di dialogo nuove credenziali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo nuove credenziali consente di creare una nuova credenziale.



== Parametri delle credenziali

È possibile impostare i seguenti parametri per la credenziale appena creata:

* *Corrispondenza*
+
Consente di selezionare il tipo di corrispondenza della credenziale, che definisce la credenziale per un indirizzo IP o un nome host specifico o per un'intera subnet o intervallo IP. È possibile selezionare una delle seguenti opzioni:

+
** Exact (esatto): Definisce le credenziali per un IP o un nome host specifico
** Modello: Definisce le credenziali per l'intervallo di nomi host o per l'intera subnet o intervallo IP
+
Pattern è un'espressione regolare utilizzata per la corrispondenza di una stringa. Ad esempio, `10.10.10.` Corrisponde a qualsiasi IP compreso tra 10.10.10.0 e 10.10.10.255, e. `host` corrisponde a tutti i nomi host che iniziano con `host`.



* *Tipo*
+
Consente di selezionare il tipo di host dall'elenco a discesa.

+

NOTE: VMware vCenter non è supportato per Linux.

* *Nome/IP*
+
Consente di specificare il nome host o l'indirizzo IP per la credenziale.

* *Nome utente*
+
Consente di specificare un nome utente per la credenziale.

* *Password*
+
Consente di specificare una password per il nome utente creato per la credenziale.

* *Sovrascrivi valori predefiniti*
+
Consente di sovrascrivere i valori predefiniti del protocollo, della porta e del timeout associati al tipo di sistema remoto selezionato per la credenziale.

+
Per impostazione predefinita, questa casella di controllo non è selezionata. Selezionare la casella di controllo se si desidera sovrascrivere i valori predefiniti.





== Pulsanti di comando

* *Test*
+
Consente di verificare la connessione all'host o all'indirizzo IP effettuando l'accesso utilizzando le credenziali richieste.

* *Salva*
+
Salva le impostazioni di configurazione e chiude la finestra di dialogo.

* *Annulla*
+
Annulla le eventuali modifiche e chiude la finestra di dialogo.


