---
permalink: help/reference-new-data-source-dialog-box.html 
sidebar: sidebar 
keywords: new, data, source, dialog box, enable, add 
summary: La finestra di dialogo Nuova origine dati consente di aggiungere una nuova origine dati. 
---
= Finestra di dialogo Nuova origine dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Nuova origine dati consente di aggiungere una nuova origine dati.



== Proprietà di configurazione origine dati

* *Nome*
+
Consente di specificare un nome per l'origine dati.

* *Tipo di origine dati*
+
Consente di selezionare il tipo di origine dati, ad esempio Active IQ Unified Manager - 6.0 (MYSQL).

+
Quando si seleziona un tipo di origine dati, la porta, lo schema, il nome utente, la password, i campi interval (minuti) e timeout (sec) vengono popolati con i dati.

+

NOTE: Se si desidera eseguire i flussi di lavoro di protezione dei dati OnCommand Workflow Automation (Wfa) da un server Active IQ Unified Manager, è necessario configurare Wfa nel server Active IQ Unified Manager.

+
Per ulteriori informazioni, consultare la _Guida in linea di Unified Manager OnCommand_.

* *Nome host*
+
Consente di specificare il nome host o l'indirizzo IP (IPv4 o IPv6) per l'origine dati.

+

NOTE: Il tipo di origine dati Active IQ Unified Manager non supporta gli indirizzi IPv6.

* *Porta*
+
Visualizza il numero di porta associato, se presente, per il tipo di origine dati selezionato.

+
È possibile modificare la porta predefinita e specificare una porta diversa per l'origine dati.

* *Schema*
+
Visualizza lo schema associato al tipo di origine dati selezionato, ad esempio _cm_storage_ per Active IQ Unified Manager - 6.0 (MYSQL).

+
Impossibile modificare questa proprietà.

* *Nome utente*
+
Visualizza il nome utente associato, se presente, per il tipo di origine dati selezionato.

+
Specificare il nome utente appropriato per questa origine dati per sovrascrivere il nome utente predefinito:

+
** Per Active IQ Unified Manager 6.0 e versioni successive, è necessario immettere il nome utente dell'account utente del database creato sul server Active IQ Unified Manager.
** Per Performance Advisor, è necessario immettere il nome utente di un utente Active IQ Unified Manager con un ruolo minimo di GlobalRead.


* *Password*
+
Consente di specificare una password per il tipo di origine dati selezionato.

+
Specificare una password per sovrascrivere la password predefinita per il nome utente di questa origine dati:

+
** Per Active IQ Unified Manager 6.0 e versioni successive, è necessario immettere la password dell'account utente del database creato sul server Active IQ Unified Manager.
** Per Performance Advisor, è necessario inserire la password di un utente Active IQ Unified Manager con un ruolo minimo di GlobalRead.


* *Database*
* *Intervallo (minuti)*
+
Consente di fare clic sul valore e selezionare un intervallo (in minuti) utilizzando le frecce su e giù.

+

NOTE: Se l'intervallo è impostato su zero (0), il campionamento automatico viene disattivato.

+
L'intervallo predefinito per il campionamento dei dati è:

+
** Tipo di origine dati basata su script: 1440 (performance e vc)
** Tipo di origine dati basata su SQL: 30 (cm_storage, storage e cm_performance)


* *Consultare la Guida alle istruzioni di installazione*
+
Apre la finestra di dialogo Setup Instruction Guide (Guida all'installazione), che consente di specificare le istruzioni per la configurazione dell'origine dati.





== Pulsanti di comando

* *Salva*
+
Salva le impostazioni di configurazione e chiude la finestra di dialogo.

* *Annulla*
+
Annulla le eventuali modifiche e chiude la finestra di dialogo.


