---
permalink: help/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: configure, oncommand, workflow, automation, use, microsoft, active, directory, lightweight, access, protocol, server, authentication, authorization 
summary: 'È possibile configurare OnCommand Workflow Automation (Wfa) in modo che utilizzi un server LDAP (Lightweight Directory Access Protocol) per l"autenticazione e l"autorizzazione.' 
---
= Configurare le impostazioni di autenticazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare OnCommand Workflow Automation (Wfa) in modo che utilizzi un server LDAP (Lightweight Directory Access Protocol) per l'autenticazione e l'autorizzazione.

*Cosa ti serve*

È necessario aver configurato un server Microsoft ad LDAP nel proprio ambiente.

*A proposito di questa attività*

Per Wfa è supportata solo l'autenticazione Microsoft ad LDAP. Non è possibile utilizzare altri metodi di autenticazione LDAP, inclusi Microsoft ad Lightweight Directory Services (ad LDS) o Microsoft Global Catalog.


NOTE: Durante la comunicazione, LDAP invia il nome utente e la password in testo normale. Tuttavia, la comunicazione LDAPS (LDAP Secure) è crittografata e sicura.

.Fasi
. Accedere a WFA tramite un browser Web come amministratore.
. Fare clic su *Impostazioni* e in *Setup* fare clic su *autenticazione*.
. Selezionare la casella di controllo *Enable Active Directory* (attiva Active Directory).
. Inserire le informazioni richieste nei campi:
+
.. *Opzionale:* se si desidera utilizzare il formato _utente@dominio_ per gli utenti di dominio, sostituire `sAMAccountName` con `userPrincipalName` Nel campo *User name Attribute*.
.. *Opzionale:* se sono richiesti valori univoci per il proprio ambiente, modificare i campi obbligatori.
.. Immettere l'URI del server ad come segue: + esempio: `ldap://active_directory_server_address\[:port\]`
+
`ldap://NB-T01.example.com[:389]`

+
Se LDAP su SSL è stato attivato, è possibile utilizzare il seguente formato URI: `ldaps://active_directory_server_address\[:port\]`

.. Aggiungere un elenco di nomi di gruppi ad ai ruoli richiesti.
+

NOTE: È possibile aggiungere un elenco di nomi di gruppi ad ai ruoli richiesti nella finestra gruppi Active Directory.



. Fare clic su *Save* (Salva).

